"""make_ownership_type_nullable

Revision ID: 367bf5d442d0
Revises: a1b2c3d4e5f6
Create Date: 2026-03-09 12:00:26.589780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '367bf5d442d0'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'building_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tenants', 'ownership_type',
               existing_type=postgresql.ENUM('בעלים', 'משכיר', 'שוכר', name='ownershiptype'),
               nullable=True)
    op.drop_index('ix_users_invite_token', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_invite_token', 'users', ['invite_token'], unique=False)
    op.alter_column('tenants', 'ownership_type',
               existing_type=postgresql.ENUM('בעלים', 'משכיר', 'שוכר', name='ownershiptype'),
               nullable=False)
    op.alter_column('tenants', 'building_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
