"""add_bank_fields_to_tenant

Revision ID: 75895bf5dce6
Revises: d329d72540d2
Create Date: 2026-02-21 15:29:19.873469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75895bf5dce6'
down_revision: Union[str, None] = 'd329d72540d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apartments', 'expected_payment',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Overrides building default if set',
               existing_nullable=True)
    op.alter_column('bank_statements', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Store original parsed data',
               existing_nullable=True)
    op.alter_column('buildings', 'expected_monthly_payment',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Default expected payment per apartment',
               existing_nullable=True)
    op.drop_constraint('uq_building_name', 'buildings', type_='unique')
    op.alter_column('name_mappings', 'bank_name',
               existing_type=sa.VARCHAR(),
               comment='Name as it appears in bank statement',
               existing_nullable=False)
    op.add_column('tenants', sa.Column('bank_name', sa.String(), nullable=True, comment='Bank name for payment matching'))
    op.add_column('tenants', sa.Column('bank_account', sa.String(), nullable=True, comment='Bank account number'))
    op.alter_column('tenants', 'name',
               existing_type=sa.VARCHAR(),
               comment='Display name (may be abbreviated)',
               existing_nullable=False)
    op.alter_column('tenants', 'full_name',
               existing_type=sa.VARCHAR(),
               comment='Full name for bank matching',
               existing_nullable=True)
    op.alter_column('tenants', 'phone',
               existing_type=sa.VARCHAR(),
               comment='Normalized to +972 format',
               existing_nullable=True)
    op.alter_column('transactions', 'description',
               existing_type=sa.VARCHAR(),
               comment='Original Hebrew text from bank',
               existing_nullable=False)
    op.alter_column('transactions', 'match_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Confidence score 0-1',
               existing_nullable=True)
    op.alter_column('transactions', 'is_confirmed',
               existing_type=sa.BOOLEAN(),
               comment='User verified this match',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'is_confirmed',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='User verified this match',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('transactions', 'match_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Confidence score 0-1',
               existing_nullable=True)
    op.alter_column('transactions', 'description',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Original Hebrew text from bank',
               existing_nullable=False)
    op.alter_column('tenants', 'phone',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Normalized to +972 format',
               existing_nullable=True)
    op.alter_column('tenants', 'full_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Full name for bank matching',
               existing_nullable=True)
    op.alter_column('tenants', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Display name (may be abbreviated)',
               existing_nullable=False)
    op.drop_column('tenants', 'bank_account')
    op.drop_column('tenants', 'bank_name')
    op.alter_column('name_mappings', 'bank_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Name as it appears in bank statement',
               existing_nullable=False)
    op.create_unique_constraint('uq_building_name', 'buildings', ['name'])
    op.alter_column('buildings', 'expected_monthly_payment',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Default expected payment per apartment',
               existing_nullable=True)
    op.alter_column('bank_statements', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Store original parsed data',
               existing_nullable=True)
    op.alter_column('apartments', 'expected_payment',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Overrides building default if set',
               existing_nullable=True)
    # ### end Alembic commands ###
